# compose file for local development
# starts backend on 8080, admin basic auth "admin:password"
# UI on http://127.0.0.1:8080/web
# set AUTH_GITHUB_CID/AUTH_GITHUB_CSEC below to enable GitHub sign-in locally
#
# build remark42 docker image - docker compose -f compose-dev-frontend.yml build
# start remark42 service - docker compose -f compose-dev-frontend.yml up

services:
  remark42:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SKIP_BACKEND_TEST=true
        - SKIP_FRONTEND_BUILD=true
        # - NODE_ENV=development

    image: ghcr.io/umputun/remark42:dev
    container_name: "remark42-dev"
    hostname: "remark42-dev"

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    ports:
      - "8080:8080" # primary rest server

    environment:
      - REMARK_URL=http://127.0.0.1:8080
      - SECRET=12345
      - DEBUG=true
      - ADMIN_PASSWD=password
      # - AUTH_GITHUB_CID=...
      # - AUTH_GITHUB_CSEC=...
    volumes:
      - ./var:/srv/var
