# compose file for local development
# starts backend on 8080, admin basic auth "admin:password"
# UI on http://127.0.0.1:8080/web
# set AUTH_GITHUB_CID/AUTH_GITHUB_CSEC below to enable GitHub sign-in locally
#
# build remark42 docker image - docker compose -f compose-dev-backend.yml build
# start remark42 service - docker compose -f compose-dev-backend.yml up

services:
  remark42:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SKIP_BACKEND_TEST
        - BACKEND_TEST_TIMEOUT
        - SKIP_FRONTEND_TEST=true
        - CI
        - GITHUB_REF
        - GITHUB_SHA
    image: ghcr.io/umputun/remark42:dev
    container_name: "remark42-dev"
    hostname: "remark42-dev"

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    ports:
      - "8080:8080" # primary rest server

    environment:
      # - APP_UID=1000
      # - TIME_ZONE=GMT
      - REMARK_URL=http://127.0.0.1:8080
      - SECRET=12345
      - DEBUG=true
      - ADMIN_PASSWD=password
      - NOTIFY_USERS
      - NOTIFY_ADMINS
      - NOTIFY_EMAIL_FROM
      - ADMIN_SHARED_EMAIL
      - SMTP_HOST
      - SMTP_USERNAME
      - SMTP_PASSWORD
      - SMTP_PORT
      - SMTP_TLS
      - EMOJI=true
      - ANON_VOTE=true
      - VOTES_IP=true
      - AUTH_GITHUB_CID=1111
      - AUTH_GITHUB_CSEC=1111
    volumes:
      - ./var:/srv/var
