# compose for running e2e tests in CI

services:
  remark42:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SKIP_BACKEND_TEST=true
        - SKIP_FRONTEND_TEST=true

    image: ghcr.io/umputun/remark42:dev
    container_name: "remark42"

    environment:
      # remark42 hostname the tests container uses to reach this service
      # (unlike local development where 127.0.0.1 is used)
      - REMARK_URL=http://remark42:8080
      - SECRET=12345
      - DEBUG=true
      - ADMIN_PASSWD=password
    volumes:
      - ./var:/srv/var

  tests:
    build:
      context: ./frontend
      dockerfile: Dockerfile.e2e
    depends_on: [remark42]
    volumes:
      - ./playwright-report:/frontend/e2e/playwright-report
